FROM ubuntu:22.04

# Install base dependencies
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y sudo curl ffmpeg git locales nano python3-pip screen ssh unzip wget autossh

# Set up locale
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# Download and install bore
RUN curl -L https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz \
    -o bore.tar.gz && \
    tar -xzf bore.tar.gz && \
    mv bore /usr/local/bin/ && \
    chmod +x /usr/local/bin/bore && \
    rm bore.tar.gz

# Configure SSH
RUN mkdir -p /run/sshd && \
    mkdir -p /root/.ssh && \
    echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFshKeW/SRrfepjUPfA8LfZRg3sqX4rKhrSXB5w6K1Li Generated By Termius' > /root/.ssh/authorized_keys && \
    chmod 700 /root/.ssh && \
    chmod 600 /root/.ssh/authorized_keys && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'ClientAliveInterval 30' >> /etc/ssh/sshd_config && \
    echo 'ClientAliveCountMax 3' >> /etc/ssh/sshd_config && \
    echo 'TCPKeepAlive yes' >> /etc/ssh/sshd_config && \
    echo 'root:choco' | chpasswd && \
    ssh-keygen -A

# Create web content
RUN mkdir -p /var/www && \
    echo "<html><body><h1>Python HTTP Server Working!</h1><p>SSH access via bore.pub tunnel</p></body></html>" > /var/www/index.html

# Create startup script with persistent tunnel
RUN echo "#!/bin/sh" > /start && \
    echo "export PORT=\${PORT:-8000}" >> /start && \
    echo "cd /var/www && python3 -m http.server \$PORT --bind 0.0.0.0 &" >> /start && \
    echo "/usr/sbin/sshd" >> /start && \
    echo "while true; do" >> /start && \
    echo "    echo \"[\$(date)] Starting tunnel...\"" >> /start && \
    echo "    bore local 22 --to bore.pub" >> /start && \
    echo "    echo \"[\$(date)] Tunnel died, restarting in 2 seconds...\"" >> /start && \
    echo "    sleep 2" >> /start && \
    echo "done" >> /start && \
    chmod +x /start

# Health check
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:$PORT/ || exit 1

ENV PORT=8000
EXPOSE $PORT 22

CMD /start
